sources:
  - module: google_shopping
    class: GoogleShoppingScraper
    enabled: true
  - module: travel
    class: TravelScraper
    enabled: true
  - module: hotel
    class: HotelScraper
    enabled: true
