sources:
  - module: duckduckgo
    class: DuckDuckGoScraper
    enabled: true
  - module: travel
    class: TravelScraper
    enabled: true
  - module: hotel
    class: HotelScraper
    enabled: true
